### ISSUE TITLE
All 0%

### ISSUE THREAD

**Issue by smolenio** [Direct5dom/SeeMyServer_Issues#1]
Hi,

I added server ssh and everything is 0% ssh connection is ok. Login and pass is ok. Do u know why it doesnt work? 

![Zrzut ekranu 2024-05-08 114902](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/fac6b77d-fbc8-42bd-b239-e13bd3c97831)
![Zrzut ekranu 2024-05-08 114837](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/21727db1-a737-4718-9e8f-6df823160644)

**Comment by Direct5dom** [comment]
Please tell me your SeeMyServer version. There was a known delimiter issue with older versions that would cause this, it was fixed in version `1.2.6`.
The version number is at the top of the About page.
You can find the log file `logfile.txt` in `C:\Users\<UserName>\.cmslogs`, please send its contents to further determine the problem.

**Comment by smolenio** [comment]
I use 1.2.6 version. In the logs, I don't see any errors. I tried it on the mobile app called ServerCat, and it works. Server config looks ok. 

[INFO] [2024-05-09 08:49:58] Id: 1, Name: jasper
[INFO] [2024-05-09 08:49:58] 1
[INFO] [2024-05-09 08:49:58] Add Config is completed.

**Comment by smolenio** [comment]
Open Terminal works.

![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/2d33efee-13a3-475b-ad87-3265e1ae988f)

**Comment by Direct5dom** [comment]
This still seems like an issue caused by the delimiter. I believe the problem with this implementation is significant, so I've switched to a new approach, which should address the issue. You can download the pre-release version 1.2.7 from below to test if the problem persists. The Microsoft Store will update later.

Please note that the version I provide here is self-signed and requires you to right-click `Install.ps1` after extraction and select "Run with PowerShell". During installation, you may be prompted to modify some Windows settings to allow side-loading. This installation method may replace the SeeMyServer installed from the Microsoft Store, so make sure to back up your data in advance (for safety, SSH passwords may need to be re-entered after import).

[CMS x64](https://drive.google.com/file/d/16bWEYzeA3qR0qyxKxU4c4AmmVKVDbeX7/view?usp=drive_link)
[CMS ARM64](https://drive.google.com/file/d/1OTjSMLgaMUHlI-FouFPua_qSamh056Ik/view?usp=drive_link)

**Comment by smolenio** [comment]
Ok, I installed it. I have version 1.2.6 and the problem persists

[INFO] [2024-05-09 11:07:19] Items removed:
[INFO] [2024-05-09 11:07:19] Id: 1, Name: jasper
[INFO] [2024-05-09 11:07:19] Delete Config is completed.
[INFO] [2024-05-09 11:07:21] Dialog field initialization completed.
[INFO] [2024-05-09 11:07:21] PrivateKeyIsOpen() completed.
[INFO] [2024-05-09 11:07:35] Items added:
[INFO] [2024-05-09 11:07:35] Id: 1, Name: Jasper
[INFO] [2024-05-09 11:07:35] 1
[INFO] [2024-05-09 11:07:35] Add Config is completed.


![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/ffb9479d-acd6-4d22-905a-70bc03db37e2)

![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/8cf7ed90-5f55-4738-82d3-d5ae418b60f7)

**Comment by Direct5dom** [comment]
Please confirm that you have installed the self-signed version of the software I provided, as it may not have installed successfully or may be coexisting with the Microsoft Store version. The version number should be 1.2.7, as seen on the About page.
![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/59590732/3f67892c-1187-475f-b08e-a53bde12f47a)

**Comment by smolenio** [comment]
Ok I ve got 1.2.7, but again 0% all

![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/c7f6e796-5f6a-49b1-a1cc-438ceef567bf)

**Comment by smolenio** [comment]
![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/1e180ad9-c613-45b7-9e51-dec7b6e522bd)

**Comment by Direct5dom** [comment]
Have you tried switching to key authentication for SSH login? Is the issue still persisting?

**Comment by smolenio** [comment]
Yes I ve tried and still persisting

**Comment by Direct5dom** [comment]
I'm sorry, I'm a bit lost at the moment. Could you please let me know which version of Linux distribution you're using? I need to try setting up a similar environment to reproduce the issue.

**Comment by smolenio** [comment]
Ok np I use Oracle Linux Server relase 7.6

**Comment by Direct5dom** [comment]
Thank you, I'll try to resolve the issue as soon as possible.

**Comment by Direct5dom** [comment]
I haven't encountered the exact same error logs as you, but there are indeed issues with the software. It seems the problem stems from my oversight; there's a flaw in the logic for encrypting and storing passwords, causing severe errors if one attempts to log in with a password initially. Additionally, there's a logical flaw with the Key Auth switch, rendering it ineffective even if switched to afterward. I have now rectified this issue and successfully retrieved system information for Oracle Linux 7.6.

![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/59590732/99e36c7c-ec8e-4d54-904c-a991a5963a14)

The download link for the self-signed version is provided below. Alternatively, you can wait for the Microsoft Store to update as it is currently undergoing certification.
Note: It's recommended to uninstall the old version before installing the new one and perform a fresh installation.

[x64](https://drive.google.com/file/d/12GEWzkkNWf4ns05eh8spM6cDdfw8FJcS/view?usp=drive_link)
[ARM64](https://drive.google.com/file/d/1xr2_6ykrKeRG07RwUR9LJln9fOryquo-/view?usp=drive_link)

**Comment by smolenio** [comment]
Monitoring of SSH is working, now it is fine. Only CPU usage monitoring is not working for me; it shows 0% all the time on every server.

![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/a2c1eafe-0489-47f5-9314-7a0c0adaf256)
![image](https://github.com/Direct5dom/SeeMyServer_Issues/assets/58400574/2a771d2b-d969-4813-9431-830d2dc230ec)

**Comment by smolenio** [comment]
The application also increases server usage by 40%.

**Comment by Direct5dom** [comment]
Sorry, I haven't replied to you in the past few weeks as I've been focusing on my graduation thesis.

I attempted to reproduce this issue, but it could not be replicated on my own server. Considering you mentioned the software increased the server load by 40%, I suspect that some SSH commands might be getting blocked. The SSH command related to CPU usage is:

```bash
cat /proc/stat | grep cpu
```

This command is very basic and theoretically should not be blocked. It returns results similar to the following:

```
cpu  67142240 105892 8503900 283396467 8439066 0 2401872 0 0 0
cpu0 12840160 23847 1825458 76252956 1806888 0 31005 0 0 0
cpu1 34908772 17829 2524936 50778273 1364404 0 2329592 0 0 0
cpu2 10611287 31643 2088971 77223775 2669928 0 18966 0 0 0
cpu3 8782020 32571 2064534 79141461 2597844 0 22307 0 0 0
```

By parsing the above results, the CPU usage can be calculated.

I have rewritten some of the logic so that if an SSH command does not receive a response, it will not continue to send SSH requests, thus preventing excessive SSH commands from significantly increasing server load. The link for the self-signed version download is below, and the Microsoft Store update will follow shortly.

[x64](https://drive.google.com/file/d/1WlMoexwES9uyc9yB-E7TCweUqq5Qcbjt/view?usp=drive_link)
[ARM64](https://drive.google.com/file/d/1AHMhDPTegpd4tM-icmSB6QR1g9Je_MiB/view?usp=drive_link)

---

The following are all the SSH requests used by this application. All commands are very basic, and I have tested them on Oracle Linux. Perhaps some of these commands might be causing blockage on your server.

```
"cat /proc/stat | grep cpu",
"cat /proc/meminfo | grep -E 'Mem|Swap'",
"cat /proc/net/dev",
"df -hP",
"uptime | awk '{print $3 \" \" $4}'",
"hostname",
"top -bn1",
"cat /proc/cpuinfo | grep processor | wc -l",
"cat /etc/*-release | grep PRETTY_NAME",
"cat /proc/diskstats",
"uname -r"
```
